#:kivy 1.9.1

<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: ''
    background_normal: 'button.jpeg'
    background_color: .88, .88, .88, 1

<CustomWidget>:
    CustButton:
        text: "Random"
        pos: root.x, 200

    CustButton:
        text: "Random 2"
        pos: 200, 400

    CustButton:
        text: "Random 3"
        pos: root.x, root.y
