#: kivy 1.9.1

<StackLayout>:
    orientation: "lr-tb"
    spacing: 10
    padding: 10

    Button:
        text: '1st'
        size_hint: None, .15
        width: 100

    Button:
        text: '2nd'
        size_hint: None, .3
        width: 120

    Button:
        text: '3rd'
        size_hint: None, .15
        width: 140

    Button:
        text: '4th'
        size_hint: .1, .6
        #width: 160

    Button:
        text: '5th'
        size_hint: None, .15
        width: 200

